# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Gigalixir Monthly Refresh

on:
  schedule: 
    - cron: "32 5 19 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  redeploy:
    name: Refresh Gigalixir
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
    - run: sudo pip install gigalixir
    - run: gigalixir login -e "${{ secrets.GIGALIXIR_EMAIL }}" -y -p "${{ secrets.GIGALIXIR_PASSWORD }}"
    - run: gigalixir ps:scale -a karaoke -r 1
